"""
03_train_personal_model.py

Purpose
-------
Train personalized wellbeing prediction models.

For every participant and every target date:

    1. Use only historical samples before the target date.
    2. Train a separate model for that participant.
    3. Retrain the model from scratch for every target date.
    4. Predict the Wellbeing Index for the target date.

Models compared
---------------
1. Random Forest Regressor
2. Gradient Boosting Regressor
3. Dummy Mean Regressor

Important
---------
- Models are trained separately for each participant.
- No participant pooling is performed.
- The target day's behavioral features are never used.
- The target day's wellbeing value is never used for training.
- Historical samples are chronological.
- No random train/test split is used.
- This is a walk-forward prediction design.
"""

from pathlib import Path
import warnings

import numpy as np
import pandas as pd

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
)
from sklearn.dummy import DummyRegressor
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline


warnings.filterwarnings("ignore")


# ============================================================
# 1. PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

ML_DIR = PROJECT_ROOT / "ML"
RESULTS_DIR = ML_DIR / "Results"

FEATURE_FILE = (
    RESULTS_DIR / "behavior_7day_features.csv"
)

WELLBEING_FILE = (
    RESULTS_DIR / "wellbeing_index.csv"
)

OUTPUT_FILE = (
    RESULTS_DIR / "personal_model_predictions.csv"
)

SUMMARY_FILE = (
    RESULTS_DIR / "personal_model_summary.csv"
)


# ============================================================
# 2. CONFIGURATION
# ============================================================

RANDOM_STATE = 42

# A model should not be trained with only a few historical
# observations. This keeps the first predictions conservative.
MIN_TRAINING_SAMPLES = 10

# Number of trees for Random Forest.
N_ESTIMATORS = 200

# Feature names are generated by script 02.
BEHAVIOR_VARIABLES = [
    "Steps",
    "Exercise_Count",
    "Exercise_Duration",
    "Exercise_Distance",
    "Exercise_Calories",
    "Exercise_Avg_HR",
    "Sleep_Hours",
    "Sleep_Duration_Score",
    "Deep_Sleep_Minutes",
    "Sleep_Restlessness",
    "Sleep_Composition",
    "Sleep_Revitalization",
    "Sleep_Score",
]

FEATURE_COLUMNS = []

for variable in BEHAVIOR_VARIABLES:
    FEATURE_COLUMNS.append(
        f"{variable}_7d_slope"
    )
    FEATURE_COLUMNS.append(
        f"{variable}_7d_change"
    )

TARGET_COLUMN = "Wellbeing_Index"


# ============================================================
# 3. MODEL BUILDERS
# ============================================================

def build_models() -> dict:
    """
    Create fresh model pipelines.

    A new set of models is created for every target date.
    """

    models = {

        "RandomForest": Pipeline(
            steps=[
                (
                    "imputer",
                    SimpleImputer(
                        strategy="median"
                    ),
                ),
                (
                    "model",
                    RandomForestRegressor(
                        n_estimators=N_ESTIMATORS,
                        random_state=RANDOM_STATE,
                        n_jobs=-1,
                        min_samples_leaf=2,
                    ),
                ),
            ]
        ),

        "GradientBoosting": Pipeline(
            steps=[
                (
                    "imputer",
                    SimpleImputer(
                        strategy="median"
                    ),
                ),
                (
                    "model",
                    GradientBoostingRegressor(
                        n_estimators=100,
                        learning_rate=0.05,
                        max_depth=2,
                        min_samples_leaf=3,
                        random_state=RANDOM_STATE,
                    ),
                ),
            ]
        ),

        "MeanBaseline": Pipeline(
            steps=[
                (
                    "imputer",
                    SimpleImputer(
                        strategy="median"
                    ),
                ),
                (
                    "model",
                    DummyRegressor(
                        strategy="mean"
                    ),
                ),
            ]
        ),
    }

    return models


# ============================================================
# 4. LOAD DATA
# ============================================================

def load_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Load behavioral features and wellbeing targets.
    """

    if not FEATURE_FILE.exists():
        raise FileNotFoundError(
            f"Feature file not found:\n{FEATURE_FILE}"
        )

    if not WELLBEING_FILE.exists():
        raise FileNotFoundError(
            f"Wellbeing file not found:\n{WELLBEING_FILE}"
        )

    features = pd.read_csv(
        FEATURE_FILE
    )

    wellbeing = pd.read_csv(
        WELLBEING_FILE
    )

    return features, wellbeing


# ============================================================
# 5. PREPARE DATA
# ============================================================

def prepare_data(
    features: pd.DataFrame,
    wellbeing: pd.DataFrame,
) -> pd.DataFrame:
    """
    Merge behavioral features with the wellbeing target.
    """

    required_feature_columns = [
        "participant_id",
        "target_date",
        *FEATURE_COLUMNS,
    ]

    missing_features = [
        column
        for column in required_feature_columns
        if column not in features.columns
    ]

    if missing_features:
        raise ValueError(
            "Missing required feature columns:\n"
            + "\n".join(missing_features)
        )

    required_wellbeing_columns = [
        "participant_id",
        "date",
        TARGET_COLUMN,
    ]

    missing_targets = [
        column
        for column in required_wellbeing_columns
        if column not in wellbeing.columns
    ]

    if missing_targets:
        raise ValueError(
            "Missing required wellbeing columns:\n"
            + "\n".join(missing_targets)
        )

    # --------------------------------------------------------
    # Date conversion
    # --------------------------------------------------------

    features = features.copy()
    wellbeing = wellbeing.copy()

    features["target_date"] = pd.to_datetime(
        features["target_date"],
        errors="coerce",
    )

    wellbeing["date"] = pd.to_datetime(
        wellbeing["date"],
        errors="coerce",
    )

    # --------------------------------------------------------
    # Keep valid rows
    # --------------------------------------------------------

    features = features.dropna(
        subset=[
            "participant_id",
            "target_date",
        ]
    )

    wellbeing = wellbeing.dropna(
        subset=[
            "participant_id",
            "date",
            TARGET_COLUMN,
        ]
    )

    # --------------------------------------------------------
    # Make participant IDs strings
    # --------------------------------------------------------

    features["participant_id"] = (
        features["participant_id"]
        .astype(str)
    )

    wellbeing["participant_id"] = (
        wellbeing["participant_id"]
        .astype(str)
    )

    # --------------------------------------------------------
    # Merge target wellbeing onto feature rows
    # --------------------------------------------------------

    merged = features.merge(
        wellbeing[
            [
                "participant_id",
                "date",
                TARGET_COLUMN,
            ]
        ],
        left_on=[
            "participant_id",
            "target_date",
        ],
        right_on=[
            "participant_id",
            "date",
        ],
        how="left",
        validate="one_to_one",
    )

    merged = merged.drop(
        columns=["date"]
    )

    merged = merged.sort_values(
        [
            "participant_id",
            "target_date",
        ]
    ).reset_index(
        drop=True
    )

    return merged


# ============================================================
# 6. TRAIN MODELS FOR ONE PARTICIPANT
# ============================================================

def train_participant_models(
    participant_df: pd.DataFrame,
) -> list[dict]:
    """
    Perform chronological walk-forward training for one participant.

    For target date T:

        Training data = all samples with date < T

    The model is freshly created and trained for every target date.
    """

    participant_df = participant_df.sort_values(
        "target_date"
    ).reset_index(
        drop=True
    )

    participant_id = (
        participant_df["participant_id"]
        .iloc[0]
    )

    dates = (
        participant_df["target_date"]
        .drop_duplicates()
        .sort_values()
        .tolist()
    )

    prediction_rows = []

    for target_date in dates:

        # ----------------------------------------------------
        # Current target row
        # ----------------------------------------------------

        current_rows = participant_df[
            participant_df["target_date"]
            == target_date
        ]

        if len(current_rows) != 1:
            continue

        current_row = current_rows.iloc[0]

        actual_value = current_row[
            TARGET_COLUMN
        ]

        # ----------------------------------------------------
        # Historical training data
        #
        # STRICTLY before target date.
        # ----------------------------------------------------

        historical = participant_df[
            participant_df["target_date"]
            < target_date
        ].copy()

        # ----------------------------------------------------
        # Target must exist for historical training samples.
        # ----------------------------------------------------

        historical = historical.dropna(
            subset=[TARGET_COLUMN]
        )

        # ----------------------------------------------------
        # Feature availability
        # ----------------------------------------------------

        historical = historical.dropna(
            subset=FEATURE_COLUMNS,
            how="all",
        )

        training_sample_count = len(
            historical
        )

        # ----------------------------------------------------
        # Cannot train before minimum history exists.
        # ----------------------------------------------------

        if (
            training_sample_count
            < MIN_TRAINING_SAMPLES
        ):

            prediction_rows.append(
                {
                    "participant_id": participant_id,
                    "target_date": target_date,
                    "actual_wellbeing": actual_value,
                    "training_samples": training_sample_count,
                    "model": "Not_Enough_History",
                    "predicted_wellbeing": np.nan,
                    "prediction_status": "Insufficient_History",
                }
            )

            continue

        # ----------------------------------------------------
        # Training matrix
        # ----------------------------------------------------

        X_train = historical[
            FEATURE_COLUMNS
        ]

        y_train = historical[
            TARGET_COLUMN
        ]

        # ----------------------------------------------------
        # Target feature row
        # ----------------------------------------------------

        X_target = pd.DataFrame(
            [
                current_row[
                    FEATURE_COLUMNS
                ].to_dict()
            ]
        )

        # ----------------------------------------------------
        # Train every model from scratch.
        # ----------------------------------------------------

        models = build_models()

        for model_name, model in models.items():

            try:

                model.fit(
                    X_train,
                    y_train,
                )

                prediction = model.predict(
                    X_target
                )[0]

                prediction_rows.append(
                    {
                        "participant_id": participant_id,
                        "target_date": target_date,
                        "actual_wellbeing": actual_value,
                        "training_samples": training_sample_count,
                        "model": model_name,
                        "predicted_wellbeing": float(
                            prediction
                        ),
                        "prediction_status": "Predicted",
                    }
                )

            except Exception as error:

                prediction_rows.append(
                    {
                        "participant_id": participant_id,
                        "target_date": target_date,
                        "actual_wellbeing": actual_value,
                        "training_samples": training_sample_count,
                        "model": model_name,
                        "predicted_wellbeing": np.nan,
                        "prediction_status": (
                            f"Model_Error: {error}"
                        ),
                    }
                )

    return prediction_rows


# ============================================================
# 7. MAIN TRAINING PIPELINE
# ============================================================

def main() -> None:

    print("=" * 80)
    print("PERSONALIZED WALK-FORWARD WELLBEING MODEL")
    print("=" * 80)

    print()
    print(
        f"Minimum training samples: "
        f"{MIN_TRAINING_SAMPLES}"
    )

    print(
        f"Behavioral features: "
        f"{len(FEATURE_COLUMNS)}"
    )

    print()

    # --------------------------------------------------------
    # Load
    # --------------------------------------------------------

    features, wellbeing = load_data()

    print(
        f"Feature rows loaded: "
        f"{len(features)}"
    )

    print(
        f"Wellbeing rows loaded: "
        f"{len(wellbeing)}"
    )

    # --------------------------------------------------------
    # Prepare
    # --------------------------------------------------------

    data = prepare_data(
        features,
        wellbeing,
    )

    print(
        f"Merged rows: "
        f"{len(data)}"
    )

    print()

    # --------------------------------------------------------
    # Process participants
    # --------------------------------------------------------

    all_predictions = []

    participant_ids = sorted(
        data["participant_id"]
        .unique()
    )

    print(
        f"Participants: "
        f"{len(participant_ids)}"
    )

    print()

    for participant_id in participant_ids:

        print("-" * 80)
        print(
            f"Participant: "
            f"{participant_id}"
        )

        participant_df = data[
            data["participant_id"]
            == participant_id
        ].copy()

        predictions = (
            train_participant_models(
                participant_df
            )
        )

        all_predictions.extend(
            predictions
        )

        predicted_count = sum(
            row["prediction_status"]
            == "Predicted"
            for row in predictions
        )

        print(
            f"  Target dates: "
            f"{len(predictions)}"
        )

        print(
            f"  Predictions: "
            f"{predicted_count}"
        )

    # --------------------------------------------------------
    # Combine predictions
    # --------------------------------------------------------

    if not all_predictions:

        raise RuntimeError(
            "No predictions were generated."
        )

    predictions_df = pd.DataFrame(
        all_predictions
    )

    predictions_df = predictions_df.sort_values(
        [
            "participant_id",
            "target_date",
            "model",
        ]
    ).reset_index(
        drop=True
    )

    # --------------------------------------------------------
    # Save predictions
    # --------------------------------------------------------

    predictions_df.to_csv(
        OUTPUT_FILE,
        index=False,
    )

    # ========================================================
    # 8. MODEL SUMMARY
    # ========================================================

    summary_rows = []

    for model_name, model_df in (
        predictions_df[
            predictions_df["prediction_status"]
            == "Predicted"
        ]
        .groupby("model")
    ):

        summary_rows.append(
            {
                "model": model_name,
                "prediction_count": len(
                    model_df
                ),
                "participant_count": (
                    model_df[
                        "participant_id"
                    ].nunique()
                ),
                "mean_training_samples": (
                    model_df[
                        "training_samples"
                    ].mean()
                ),
                "median_training_samples": (
                    model_df[
                        "training_samples"
                    ].median()
                ),
            }
        )

    summary_df = pd.DataFrame(
        summary_rows
    )

    summary_df.to_csv(
        SUMMARY_FILE,
        index=False,
    )

    # ========================================================
    # 9. FINAL REPORT
    # ========================================================

    print()
    print("=" * 80)
    print("COMPLETED")
    print("=" * 80)

    print(
        f"Total prediction rows: "
        f"{len(predictions_df)}"
    )

    print(
        f"Successful predictions: "
        f"{(
            predictions_df["prediction_status"]
            == "Predicted"
        ).sum()}"
    )

    print(
        f"Insufficient-history rows: "
        f"{(
            predictions_df["prediction_status"]
            == "Insufficient_History"
        ).sum()}"
    )

    print()
    print("Models:")
    print("  - RandomForest")
    print("  - GradientBoosting")
    print("  - MeanBaseline")

    print()
    print("Output:")
    print(
        f"  {OUTPUT_FILE}"
    )

    print()
    print("Summary:")
    print(
        f"  {SUMMARY_FILE}"
    )


# ============================================================
# 10. RUN
# ============================================================

if __name__ == "__main__":
    main()
