Purpose
-------
Train a personalized Random Forest model for each participant
to predict that participant's daily Wellbeing Index.

Prediction design
-----------------
For each participant and each target date:

    Training data:
        all previous target dates only

    Prediction:
        Wellbeing Index on the current target date

The model is retrained from scratch for every target date.

This creates a chronological walk-forward prediction system.

Important
---------
- One model per participant.
- No participant pooling.
- No random train/test split.
- No future information is used.
- The target day's behavioral features are used only for prediction.
- The target day's wellbeing value is never included in training.
- Missing feature values are handled with median imputation.
- Random Forest is the only predictive model.
"""

from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline


# ============================================================
# 1. PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

ML_DIR = PROJECT_ROOT / "ML"
RESULTS_DIR = ML_DIR / "Results"

FEATURE_FILE = (
    RESULTS_DIR / "behavior_7day_features.csv"
)

WELLBEING_FILE = (
    RESULTS_DIR / "wellbeing_index.csv"
)

OUTPUT_FILE = (
    RESULTS_DIR / "personal_model_predictions.csv"
)

SUMMARY_FILE = (
    RESULTS_DIR / "personal_model_summary.csv"
)


# ============================================================
# 2. CONFIGURATION
# ============================================================

RANDOM_STATE = 42

N_ESTIMATORS = 200

MIN_TRAINING_SAMPLES = 10


BEHAVIOR_VARIABLES = [
    "Steps",
    "Exercise_Count",
    "Exercise_Duration",
    "Exercise_Distance",
    "Exercise_Calories",
    "Exercise_Avg_HR",
    "Sleep_Hours",
    "Sleep_Duration_Score",
    "Deep_Sleep_Minutes",
    "Sleep_Restlessness",
    "Sleep_Composition",
    "Sleep_Revitalization",
    "Sleep_Score",
]


# ------------------------------------------------------------
# Build the 26 behavioral features generated by script 02.
# ------------------------------------------------------------

FEATURE_COLUMNS = []

for variable in BEHAVIOR_VARIABLES:

    FEATURE_COLUMNS.append(
        f"{variable}_7d_slope"
    )

    FEATURE_COLUMNS.append(
        f"{variable}_7d_change"
    )


TARGET_COLUMN = "Wellbeing_Index"


# ============================================================
# 3. BUILD RANDOM FOREST PIPELINE
# ============================================================

def build_model() -> Pipeline:
    """
    Create a fresh Random Forest pipeline.

    The model is intentionally created inside the prediction
    loop so that every target date receives a newly trained
    model.
    """

    model = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(
                    strategy="median"
                ),
            ),
            (
                "random_forest",
                RandomForestRegressor(
                    n_estimators=N_ESTIMATORS,
                    random_state=RANDOM_STATE,
                    n_jobs=-1,
                    min_samples_leaf=2,
                ),
            ),
        ]
    )

    return model


# ============================================================
# 4. LOAD INPUT FILES
# ============================================================

def load_input_data() -> tuple[
    pd.DataFrame,
    pd.DataFrame,
]:
    """
    Load behavioral features and wellbeing index.
    """

    if not FEATURE_FILE.exists():

        raise FileNotFoundError(
            f"Behavior feature file not found:\n"
            f"{FEATURE_FILE}"
        )

    if not WELLBEING_FILE.exists():

        raise FileNotFoundError(
            f"Wellbeing index file not found:\n"
            f"{WELLBEING_FILE}"
        )

    features = pd.read_csv(
        FEATURE_FILE
    )

    wellbeing = pd.read_csv(
        WELLBEING_FILE
    )

    return features, wellbeing


# ============================================================
# 5. VALIDATE INPUT COLUMNS
# ============================================================

def validate_columns(
    features: pd.DataFrame,
    wellbeing: pd.DataFrame,
) -> None:
    """
    Check that all required columns exist.
    """

    required_feature_columns = [
        "participant_id",
        "target_date",
        *FEATURE_COLUMNS,
    ]

    missing_features = [
        column
        for column in required_feature_columns
        if column not in features.columns
    ]

    if missing_features:

        raise ValueError(
            "Missing feature columns:\n"
            + "\n".join(missing_features)
        )

    required_wellbeing_columns = [
        "participant_id",
        "date",
        TARGET_COLUMN,
    ]

    missing_wellbeing = [
        column
        for column in required_wellbeing_columns
        if column not in wellbeing.columns
    ]

    if missing_wellbeing:

        raise ValueError(
            "Missing wellbeing columns:\n"
            + "\n".join(missing_wellbeing)
        )


# ============================================================
# 6. PREPARE AND MERGE DATA
# ============================================================

def prepare_data(
    features: pd.DataFrame,
    wellbeing: pd.DataFrame,
) -> pd.DataFrame:
    """
    Prepare dates, participant IDs and merge the target.

    Each behavioral feature row is matched with the wellbeing
    value for the same participant and target date.
    """

    validate_columns(
        features,
        wellbeing,
    )

    features = features.copy()
    wellbeing = wellbeing.copy()

    # --------------------------------------------------------
    # Convert dates
    # --------------------------------------------------------

    features["target_date"] = pd.to_datetime(
        features["target_date"],
        errors="coerce",
    )

    wellbeing["date"] = pd.to_datetime(
        wellbeing["date"],
        errors="coerce",
    )

    # --------------------------------------------------------
    # Remove rows without valid identifiers/dates
    # --------------------------------------------------------

    features = features.dropna(
        subset=[
            "participant_id",
            "target_date",
        ]
    )

    wellbeing = wellbeing.dropna(
        subset=[
            "participant_id",
            "date",
        ]
    )

    # --------------------------------------------------------
    # Standardize participant ID type
    # --------------------------------------------------------

    features["participant_id"] = (
        features["participant_id"]
        .astype(str)
    )

    wellbeing["participant_id"] = (
        wellbeing["participant_id"]
        .astype(str)
    )

    # --------------------------------------------------------
    # Convert target to numeric
    # --------------------------------------------------------

    wellbeing[TARGET_COLUMN] = pd.to_numeric(
        wellbeing[TARGET_COLUMN],
        errors="coerce",
    )

    # --------------------------------------------------------
    # Check duplicate participant/date targets.
    #
    # There must be only one wellbeing target for each
    # participant and date.
    # --------------------------------------------------------

    duplicate_targets = (
        wellbeing.duplicated(
            subset=[
                "participant_id",
                "date",
            ],
            keep=False,
        )
    )

    if duplicate_targets.any():

        duplicate_rows = (
            wellbeing.loc[
                duplicate_targets,
                [
                    "participant_id",
                    "date",
                ],
            ]
            .drop_duplicates()
        )

        raise ValueError(
            "Duplicate participant/date wellbeing targets "
            "were found.\n"
            f"Examples:\n{duplicate_rows.head(10)}"
        )

    # --------------------------------------------------------
    # Merge wellbeing target onto behavioral features.
    # --------------------------------------------------------

    merged = features.merge(
        wellbeing[
            [
                "participant_id",
                "date",
                TARGET_COLUMN,
            ]
        ],
        left_on=[
            "participant_id",
            "target_date",
        ],
        right_on=[
            "participant_id",
            "date",
        ],
        how="left",
        validate="one_to_one",
    )

    merged = merged.drop(
        columns=["date"]
    )

    # --------------------------------------------------------
    # Sort chronologically.
    # --------------------------------------------------------

    merged = merged.sort_values(
        [
            "participant_id",
            "target_date",
        ]
    ).reset_index(
        drop=True
    )

    return merged


# ============================================================
# 7. WALK-FORWARD TRAINING FOR ONE PARTICIPANT
# ============================================================

def train_for_participant(
    participant_df: pd.DataFrame,
) -> list[dict]:
    """
    Generate chronological predictions for one participant.

    For target date T:

        train on dates < T
        predict date T

    The model is rebuilt and retrained from scratch for
    every target date.
    """

    participant_df = participant_df.sort_values(
        "target_date"
    ).reset_index(
        drop=True
    )

    participant_id = str(
        participant_df[
            "participant_id"
        ].iloc[0]
    )

    target_dates = (
        participant_df[
            "target_date"
        ]
        .drop_duplicates()
        .sort_values()
        .tolist()
    )

    predictions = []

    for target_date in target_dates:

        # ====================================================
        # CURRENT TARGET ROW
        # ====================================================

        target_rows = participant_df[
            participant_df["target_date"]
            == target_date
        ]

        if len(target_rows) != 1:

            continue

        target_row = target_rows.iloc[0]

        actual_wellbeing = target_row[
            TARGET_COLUMN
        ]

        # ====================================================
        # HISTORICAL TRAINING DATA
        # ====================================================

        historical = participant_df[
            participant_df["target_date"]
            < target_date
        ].copy()

        # A training observation must have a known target.
        historical = historical.dropna(
            subset=[
                TARGET_COLUMN
            ]
        )

        # Remove rows where ALL behavioral features
        # are missing.
        historical = historical.dropna(
            subset=FEATURE_COLUMNS,
            how="all",
        )

        training_samples = len(
            historical
        )

        # ====================================================
        # NOT ENOUGH HISTORY
        # ====================================================

        if training_samples < MIN_TRAINING_SAMPLES:

            predictions.append(
                {
                    "participant_id": participant_id,
                    "target_date": target_date,
                    "actual_wellbeing": actual_wellbeing,
                    "training_samples": training_samples,
                    "predicted_wellbeing": np.nan,
                    "prediction_status": (
                        "Insufficient_History"
                    ),
                }
            )

            continue

        # ====================================================
        # TRAINING DATA
        # ====================================================

        X_train = historical[
            FEATURE_COLUMNS
        ].copy()

        y_train = historical[
            TARGET_COLUMN
        ].copy()

        # ====================================================
        # TARGET-DATE FEATURES
        # ====================================================

        X_target = pd.DataFrame(
            [
                target_row[
                    FEATURE_COLUMNS
                ].to_dict()
            ]
        )

        # ----------------------------------------------------
        # If absolutely all target features are missing,
        # a behavioral prediction cannot be made.
        # ----------------------------------------------------

        if X_target[
            FEATURE_COLUMNS
        ].isna().all(axis=1).iloc[0]:

            predictions.append(
                {
                    "participant_id": participant_id,
                    "target_date": target_date,
                    "actual_wellbeing": actual_wellbeing,
                    "training_samples": training_samples,
                    "predicted_wellbeing": np.nan,
                    "prediction_status": (
                        "Missing_Target_Features"
                    ),
                }
            )

            continue

        # ====================================================
        # CREATE A COMPLETELY NEW MODEL
        # ====================================================

        model = build_model()

        try:

            model.fit(
                X_train,
                y_train,
            )

            predicted_wellbeing = float(
                model.predict(
                    X_target
                )[0]
            )

            predictions.append(
                {
                    "participant_id": participant_id,
                    "target_date": target_date,
                    "actual_wellbeing": actual_wellbeing,
                    "training_samples": training_samples,
                    "predicted_wellbeing": (
                        predicted_wellbeing
                    ),
                    "prediction_status": (
                        "Predicted"
                    ),
                }
            )

        except Exception as error:

            predictions.append(
                {
                    "participant_id": participant_id,
                    "target_date": target_date,
                    "actual_wellbeing": actual_wellbeing,
                    "training_samples": training_samples,
                    "predicted_wellbeing": np.nan,
                    "prediction_status": (
                        f"Model_Error: {error}"
                    ),
                }
            )

    return predictions


# ============================================================
# 8. BUILD SUMMARY
# ============================================================

def build_summary(
    predictions_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build participant-level model summary.
    """

    rows = []

    for participant_id, participant_df in (
        predictions_df.groupby(
            "participant_id"
        )
    ):

        successful = participant_df[
            participant_df[
                "prediction_status"
            ]
            == "Predicted"
        ]

        rows.append(
            {
                "participant_id": participant_id,
                "target_dates": len(
                    participant_df
                ),
                "successful_predictions": len(
                    successful
                ),
                "insufficient_history": int(
                    (
                        participant_df[
                            "prediction_status"
                        ]
                        == "Insufficient_History"
                    ).sum()
                ),
                "missing_target_features": int(
                    (
                        participant_df[
                            "prediction_status"
                        ]
                        == "Missing_Target_Features"
                    ).sum()
                ),
                "mean_training_samples": (
                    successful[
                        "training_samples"
                    ].mean()
                    if not successful.empty
                    else np.nan
                ),
                "median_training_samples": (
                    successful[
                        "training_samples"
                    ].median()
                    if not successful.empty
                    else np.nan
                ),
            }
        )

    return pd.DataFrame(rows)


# ============================================================
# 9. MAIN
# ============================================================

def main() -> None:

    print("=" * 80)
    print("PERSONALIZED RANDOM FOREST WELLBEING PREDICTION")
    print("=" * 80)

    print()
    print(
        f"Behavioral variables: "
        f"{len(BEHAVIOR_VARIABLES)}"
    )

    print(
        f"Behavioral features: "
        f"{len(FEATURE_COLUMNS)}"
    )

    print(
        f"Minimum training samples: "
        f"{MIN_TRAINING_SAMPLES}"
    )

    print(
        f"Random Forest trees: "
        f"{N_ESTIMATORS}"
    )

    print()

    # ========================================================
    # LOAD
    # ========================================================

    features, wellbeing = (
        load_input_data()
    )

    print(
        f"Behavior feature rows: "
        f"{len(features)}"
    )

    print(
        f"Wellbeing rows: "
        f"{len(wellbeing)}"
    )

    # ========================================================
    # PREPARE
    # ========================================================

    data = prepare_data(
        features,
        wellbeing,
    )

    print(
        f"Merged prediction rows: "
        f"{len(data)}"
    )

    print()

    # ========================================================
    # PARTICIPANTS
    # ========================================================

    participant_ids = sorted(
        data[
            "participant_id"
        ]
        .unique()
    )

    print(
        f"Participants: "
        f"{len(participant_ids)}"
    )

    print()

    all_predictions = []

    # ========================================================
    # PERSONALIZED WALK-FORWARD MODELING
    # ========================================================

    for participant_id in participant_ids:

        participant_df = data[
            data["participant_id"]
            == participant_id
        ].copy()

        predictions = (
            train_for_participant(
                participant_df
            )
        )

        all_predictions.extend(
            predictions
        )

        successful = sum(
            row[
                "prediction_status"
            ]
            == "Predicted"
            for row in predictions
        )

        print(
            f"{participant_id}: "
            f"{successful} predictions / "
            f"{len(predictions)} target dates"
        )

    # ========================================================
    # CHECK RESULTS
    # ========================================================

    if not all_predictions:

        raise RuntimeError(
            "No prediction records were generated."
        )

    predictions_df = pd.DataFrame(
        all_predictions
    )

    predictions_df = predictions_df.sort_values(
        [
            "participant_id",
            "target_date",
        ]
    ).reset_index(
        drop=True
    )

    # ========================================================
    # SAVE PREDICTIONS
    # ========================================================

    predictions_df.to_csv(
        OUTPUT_FILE,
        index=False,
    )

    # ========================================================
    # SAVE SUMMARY
    # ========================================================

    summary_df = build_summary(
        predictions_df
    )

    summary_df.to_csv(
        SUMMARY_FILE,
        index=False,
    )

    # ========================================================
    # FINAL REPORT
    # ========================================================

    successful_count = int(
        (
            predictions_df[
                "prediction_status"
            ]
            == "Predicted"
        ).sum()
    )

    insufficient_count = int(
        (
            predictions_df[
                "prediction_status"
            ]
            == "Insufficient_History"
        ).sum()
    )

    missing_feature_count = int(
        (
            predictions_df[
                "prediction_status"
            ]
            == "Missing_Target_Features"
        ).sum()
    )

    print()
    print("=" * 80)
    print("COMPLETED")
    print("=" * 80)

    print(
        f"Total target dates: "
        f"{len(predictions_df)}"
    )

    print(
        f"Successful predictions: "
        f"{successful_count}"
    )

    print(
        f"Insufficient history: "
        f"{insufficient_count}"
    )

    print(
        f"Missing target features: "
        f"{missing_feature_count}"
    )

    print()
    print(
        "Model: Random Forest Regressor"
    )

    print()
    print(
        f"Predictions saved to:\n"
        f"  {OUTPUT_FILE}"
    )

    print()
    print(
        f"Summary saved to:\n"
        f"  {SUMMARY_FILE}"
    )


# ============================================================
# 10. RUN
# ============================================================

if __name__ == "__main__":
    main()
